### PR TITLE
Make sure ./lib is in sync with ./src in the CI pipeline

### LINKED ISSUE #34: Add check to CI pipeline to ensure that ./lib is in sync with ./src
https://github.com/ZencashOfficial/zencashjs/commit/98a7327c9cc16b61438421ec7fc58dd63bbd4ab5 was forgotten in https://github.com/ZencashOfficial/zencashjs/pull/32 requiring a force push to fix. Not the nice way to do it but the alternative would have been to do another release v1.2.4 for this simple change.

So for the future we need a check in the CI pipeline to ensure `./lib` was regenerated before merging to master.

### PR DESCRIPTION
**Pull request by jonahion**
fix #34

### CODE REVIEW

**Comment by lander86** [comment]
Hello @jonahion ,

thanks for your work. Unfortunately we would like to achieve the goal without installing any new dependency. I see also that you is running the "build" command and there is no need to do that (and we don't want to).
You could create just a bash script using git commands and travis-ci env variables to compare the files into the ./src folder with 
the files in the ./lib folder ; if anything in the ./src folder ha been modified, you will need to modify also the ./lib files.
If ./lib and ./src will be different, the ci pipeline needs to exit with non 0 code.

**Comment by jonahion** [comment]
Hi @lander86,

Thanks for your feedback!
The idea behind adding the dependency was to make the lib sync check in a git hook, before changes are pushed but I understand you'd better keep the number of dependencies low.

I have updated the changes to be in line with your suggestions, please have another look.

**Review by cronicc — APPROVED** [review]

**Comment by cronicc** [comment]
@jonahion Great work!

@lander86 please squash and merge, after bring development branch in sync with master.

@angievi bounty for https://github.com/HorizenOfficial/zencashjs/issues/34 can be paid out and issue can be closed once merged.

**Comment by jonahion** [comment]
Cool, thanks @cronicc!

**Pull request merged**
